export const archiveMessages = [
  // Archive, history, photographs, and file provenance.
  "Bringing another frame into focus…",
  "Looking through the archive…",
  "Somewhere in the contact sheet…",
  "A glimpse from another time…",
  "Turning a page in the archive…",
  "Looking past the edges…",
  "A brief pause in the darkroom…",
  "Waiting for the image to develop…",
  "Another exposure awaits…",
  "Following a loose thread…",
  "A detail worth a second look…",
  "Somewhere beyond the viewfinder…",
  "A small window into elsewhere…",
  "Looking between the negatives…",
  "A frame from somewhere else…",
  "One more glimpse…",
  "An unplanned composition…",
  "A pause before the next exposure…",
  "A little light from elsewhere…",
  "Off the beaten contact sheet…",
  "At the edge of the archive…",
  "An unexpected point of view…",
  "Looking for a different angle…",
  "Another corner of the internet…",
  "Pulling a frame from the stack…",
  "An image without its caption…",
  "A page we haven't opened…",
  "Somewhere in an unnamed folder…",
  "A loose print from the archive…",
  "A moment someone left behind…",
  "Opening an old contact sheet…",
  "One frame, very little context…",
  "Looking through the unsorted pile…",
  "An exposure with a missing date…",
  "A scene outside our usual route…",
  "A picture far from its source…",
  "Opening another digital time capsule…",
  "Disturbing the digital sediment…",
  "Excavating old pixels…",
  "Archaeology, but with screenshots…",
  "Digging through digital fossils…",
  "Unearthing a little history…",
  "A file with its own history…",
  "Looking beyond the filenames…",
  "Opening the folder within the folder…",
  "Descending another directory level…",
  "Searching past the backups…",
  "Looking beyond copy (3)…",
  "Checking somewhere past screenshots…",
  "Looking for accidental composition…",
  "Searching for accidental cinema…",
  "Looking for a trace of a story…",
  "Finding a scene between the scenes…",
  "A view from the cutting room floor…",
  "A frame without the rest of the reel…",
  "An image with the date worn off…",
  "Something outside the usual crop…",
  "A glimpse between the takes…",
  "A picture without the backstory…",
  "A forgotten corner of the screen…",
  "Following the grain…",
  "Looking for the light in this one…",
  "Another scene from the pile…",
  "Waiting at the edge of the lens…",
  "A shot from outside the sequence…",
  "A small find in a large archive…",
  "A print without a place in the album…",
  "Turning over another loose frame…",
  "Lifting the tissue between prints…",
  "A pencil note on the reverse…",
  "Sliding a negative toward the light…",
  "A reel from the lower shelf…",
  "Checking the sleeve for a date…",
  "Light caught on an ordinary day…",
  "A street kept in a photograph…",
  "Dust along the binding…",
  "A face outside the caption…",
  "The stamp outlasted the address…",
  "A thumbprint on the border…",
  "An envelope full of afternoons…",
  "A date in someone else's hand…",
  "A crease through the background…",
  "The margin holds a pencil mark…",
  "Reading the light on an old wall…",
  "A print slipped between pages…",
  "An afternoon on a strip of film…",
  "A small room kept in silver…",
  "A label loosening at the corner…",
  "One shutter click, years later…",
  "A landscape filed under numbers…",
  "A building before its new name…",
  "A shelf with uneven stacks…",
  "A scene kept by the scanner…",
  "An old export coming through…",
  "A photograph behind the paperwork…",
  "A handwritten place we can't read…",
  "A roll that took the long way…",
  "A picture carried between machines…",
  "A familiar street at another date…",
  "A corner the photographer kept…",
  "A shadow across the emulsion…",
  "A sleeve with room for one more…",
  "A small rectangle of daylight…",
  "A view from before the renovation…",
  "A scan with its borders intact…",
  "The background has its own history…",
  "An album held together by habit…",
  "A photograph waiting in an envelope…",
  "A detail the caption passed over…",
  "A chair at the edge of a shot…",
  "A window in someone else's day…",
  "A pause recorded on film…",
  "A snapshot kept through several moves…",
  "The paper remembers the fold…",
  "A horizon from a different decade…",
  "A print that missed the exhibition…",
  "A crop made before this screen…",
  "Someone stood here with a camera…",
  "A few seconds kept from a reel…",
  "A doorway in an old exposure…",
  "A file carried through the years…",
  "A scene just off the index…",
  "A numbered box on a high shelf…",
  "A copy with a faint border…",
  "The scan catches a little dust…",
  "A brief record of the weather…",
  "The afternoon survived the upload…",
  "A photograph with softened corners…",
  "Reading an old image in new light…",
  "A trace left by the lens…",
  "The shelf ends further along…",
  "A sheet held up to the light…",
  "A few marks from the handling…",
  "A quiet scene in a crowded box…",
  "A print passed between hands…",
  "The label names a different town…",
  "A scene copied off an old drive…",
  "An instant kept beyond its day…",
  "A reflection on a strip of film…",
  "The edges show a little age…",
  "A record of where the light fell…",
  "A camera stopped here once…",
  "One rectangle from a longer reel…",
  "A photograph awaiting a caption…",
  "A street before the signs changed…",
  "A view the album couldn't fit…",
  "A small mark beside the frame…",
  "A loose end in the catalogue…",
  "A contact print under the lamp…",
  "The folder kept the original name…",
  "A box with a crossed-out label…",
  "An image behind a faded tab…",
  "A few seconds from another room…",
  "A print under the last divider…",
  "A border the crop left behind…",
  "A scene held in a glass plate…",
  "A photograph between two receipts…",
  "A detail near the sprocket holes…",

  // Paper records and storage.
  "Someone pencilled in the year",
  "Before this was a file",
  "Checking the back of the photograph",
  "An address under the mount",
  "Dates don't tell the whole story",
  "Between the cardboard dividers",
  "Ink rubbed off the label",
  "Someone numbered these by hand",
  "Stored flat, remembered otherwise",
  "The box has been moved before",
  "Under a layer of tracing paper",
  "Written on the wrong envelope",
  "Both copies have the same crease",
  "Past the last dated entry",
  "Filed by place, found by chance",
  "This drawer closes reluctantly",
  "Still in its original sleeve",
  "The index stops at a surname",
  "Several summers in one packet",
  "Taken before anyone kept a backup",
  "At the back of a shallow cabinet",
  "Someone saved the less sharp copy",
  "Held down by a paperweight",
  "Nothing written on the reverse",
  "The envelope travelled further",
  "Two dates, neither explained",
  "Copied from an older catalogue",
  "Its place in the album is empty",
  "Under the tissue, another image",
  "Kept with the correspondence",
  "The stamp says where it went",
  "That handwriting belongs to someone",
  "Once pinned above a desk",
  "Filed after the people moved away",
  "The album opens at this page",
  "Somebody cut around the border",
  "Looking under the accession slip",
  "The record has a second page",
  "Returned to a different box",
  "Only the pencil marks remain clear",

  // Film, light, and the camera.
  "Someone circled this exposure",
  "Light through an old enlarger",
  "Thirty-six chances on one roll",
  "Before the shutter closed",
  "Waiting on the far side of the lens",
  "Silver held onto the light",
  "Past the unexposed leader",
  "Shadows in the lower corner",
  "Someone metered for the window",
  "The flash reached the back wall",
  "Outside the plane of focus",
  "One exposure after the good one",
  "Grain where the details should be",
  "The edge includes a little sky",
  "Colour left in an old slide",
  "Taken at the end of the light",
  "Across a sheet of small exposures",
  "Where the negative meets its sleeve",
  "The camera pointed this way once",
  "Still inside the film gate",
  "Something beyond the focal plane",
  "A reflection caught twice",
  "The light came from an open door",
  "Scanning past the frame number",
  "Contact sheets reward a second look",
  "Someone waited for the clouds",
  "The lens kept a trace of the room",
  "Part of a much wider photograph",
  "Exposure notes in the margin",
  "The timer went off without us",
  "There was more outside the crop",
  "Along the perforated edge",
  "Last light on the contact print",
  "Holding the slide by its edges",
  "The meter favoured the bright side",
  "Before the print reached the tray",
  "An ordinary scene at f/8",
  "There used to be a darkroom here",
  "Focus fell just behind the subject",
  "Shot through a half-open window",
  "Still legible in the shadows",
  "Dust caught between scan and print",

  // Scans and digital copies.
  "Under glass since another decade",
  "The scan includes the paper's edge",
  "Earlier than the upload date",
  "Somebody's afternoon, digitised",
  "What survived the last export",
  "The photograph predates the folder",
  "From a drive nobody uses now",
  "Copied without the original notes",
  "Before the filename changed",
  "Image data from another machine",
  "The oldest copy has a different name",
  "Transferred with the rest of the box",
  "A scan beside its original",
  "The timestamp came much later",
  "At the end of an old disc",
  "Past a directory of dated exports",
  "Someone kept the unedited version",
  "The picture outlived its software",
  "An early scan with visible grain",
  "Reading a name from an old label",
  "The index card has more to say",
  "Preserved in a common file format",
  "Carried forward with the backups",
  "The source has changed addresses",
  "That extension wasn't always there",
  "An image on its second medium",
  "Paper first, pixels later",
  "The upload left the border in",
  "It came over with the other files",
  "Unpacking a saved piece of light",

  // Places and traces of ordinary days.
  "No one recorded the weather",
  "Everyone stood still for a moment",
  "Taken before the sign came down",
  "The room had different furniture",
  "Someone waited at that crossing",
  "Behind the subject, an old shopfront",
  "Nobody labelled the person at left",
  "The street hasn't kept this view",
  "That tree was shorter then",
  "Whoever held the camera stood here",
  "Before the paint was changed",
  "People passed beyond the frame",
  "The photographer caught the bus stop",
  "An earlier arrangement of this room",
  "Someone left a coat on that chair",
  "The caption only names the building",
  "Once, this was the current view",
  "Traffic on a road with its old name",
  "Nothing special about the day",
  "The picture kept the scaffolding",
  "Summer before the extension",
  "A courtyard before the parked cars",
  "Someone was just passing through",
  "The shutters were open that day",
  "Now stored under a catalogue number",
  "That doorway used to lead somewhere",
  "Midday by the length of the shadows",
  "What the person behind the lens saw",
  "Before this window was boarded up",
  "The photograph leaves the door open",
  "Rain was drying on the pavement",
  "The backdrop stayed after the shoot",
  "From the edge of someone's holiday",
  "Paint peeling behind the subject",
  "Kept after the place was renamed",
  "Another season on the same street",
  "Time passed outside this exposure",
  "An incidental record of a roofline",
  "The paper carries a little foxing",
  "Inside a packet tied with string",
  "Someone folded it to fit a pocket",
  "Two pinholes above the picture",
  "The matte finish caught a mark",
  "Filed beside a typed description",
  "The original caption is underneath",
  "Last in a bundle of loose prints",
  "The archive kept the empty street",
  "There is light in the upper window",
];
