export const easterEggMessages = [
  // Rare references, workplace risk, and mildly cursed archive material.
  "The owls are not what they seem…",
  "Life, the universe, and this frame…",
  "There is no spoon. Just pixels…",
  "These may be the frames you seek…",
  "Checking if this is safe for work…",
  "Avoiding career-ending material…",
  "Looking for a frame HR would allow…",
  "Probably safe. Probably…",
  "Attempting responsible randomness…",
  "Please remain professionally calm…",
  "Consulting an imaginary moderator…",
  "Rolling for workplace compatibility…",
  "The next frame has no references…",
  "Hoping your boss likes abstract art…",
  "An awkward screenshot is possible…",
  "Your browser history has questions…",
  "Checking workplace compatibility…",
  "An informal NSFW risk assessment…",
  "Looking for something safe-ish…",
  "Does this need an explanation…?",
  "Looking for something HR-neutral…",
  "Attempting professional randomness…",
  "Would legal tolerate this frame…?",
  "Hoping this suits a screen share…",
  "Trying not to summon HR…",
  "Keeping things reasonably employable…",
  "Hoping your manager walks past…",
  "Seeking plausible deniability…",
  "This may be difficult to explain…",
  "Context would not help anyway…",
  "We can explain. Probably…",
  "You saw nothing…",
  "Nothing to report here…",
  "Please remain professionally composed…",
  "Dignity not guaranteed…",
  "The archive knows what you did…",
  "Some files were best left forgotten…",
  "The archive has seen things…",
  "The archive refuses to elaborate…",
  "Some folders deserve caution…",
  "EXIF has entered the chat…",
  "CSS cannot save us now…",
  "The happy path remains theoretical…",
  "Searching outside the test coverage…",
  "Emotionally complex promise pending…",
  "The next frame has asked for a lawyer…",
  "This JPEG has diplomatic immunity…",
  "The contact sheet pleads the fifth…",
  "Your screen share adds stakes…",
  "The meeting chose an interesting time…",
  "A polite cough may follow…",
  "The agenda didn't mention this…",
  "A file best opened after standup…",
  "The projector makes this communal…",
  "The filename provides no alibi…",
  "HR prefers a smaller sample size…",
  "Your manager has peripheral vision…",
  "A discreet glance at the audience…",
  "The archive lacks a dress code…",
  "This folder missed orientation…",
  "A screensaver might be more prudent…",
  "The office Wi-Fi picked today…",
  "An innocent tab in difficult company…",
  "The presenter view has limits…",
  "A brief test of meeting etiquette…",
  "The crop may carry the explanation…",
  "The boardroom wasn't the target venue…",
  "Someone may ask about the source…",
  "A file with poor interview manners…",
  "The risk register needs a thumbnail…",
  "An awkward silence needs no caption…",
  "The title sounded perfectly ordinary…",
  "Safe for work is a broad brief…",
  "The audience makes this interesting…",
  "A small gamble on office culture…",
  "The folder was marked personal…",
  "A preview for a smaller window…",
  "The compliance slide comes later…",
  "A frame beyond the approved deck…",
  "We may call this visual research…",
  "The mute button won't help much…",
  "An impromptu lesson in tab selection…",
  "The chair turns toward your screen…",
  "Your résumé omitted this collection…",
  "A file with questionable references…",
  "The offsite album stayed on site…",
  "Nobody requested a live demonstration…",
  "The witness is a lossless PNG…",

  // Mildly cursed archive.
  "There were fewer boxes yesterday",
  "Someone filed this under tomorrow",
  "This room has too many windows",
  "The accession book skips this number",
  "Keep the scan. Return the envelope",
  "We don't catalogue that drawer",
  "Both sides of the negative face out",
  "Dust stops before it reaches this print",
  "There is a date on the unexposed film",
  "The handwriting is on the emulsion",
  "That cabinet isn't in the floor plan",
  "Leave the second set of keys there",
  "Nobody remembers ordering this scan",
  "Every copy has a different background",
  "The shadow appears in the next frame",
  "It was catalogued before it was taken",
  "Somebody added a door to the index",
  "The darkroom light was already on",
  "This sleeve was sealed from inside",
  "We counted the stairs on the way down",
  "Don't file it under your own name",
  "The empty box has a return address",
  "We've seen that chair in another room",
  "One photograph too many in the packet",
  "The watermark wasn't there before",
  "Nobody sat for the second portrait",
  "That margin gets wider on each copy",
  "The frame number is in your handwriting",
  "Do not compare the two negatives",
  "The return slip has today's date",

  // Workplace and screen-sharing risk.
  "Sharing your screen adds an audience",
  "Maybe close the quarterly report first",
  "The meeting is about to get visual",
  "An unusual choice for the lobby display",
  "Your colleagues can see this tab",
  "An offsite photo with onsite consequences",
  "Research is a generous description",
  "The agenda has room for an explanation",
  "Nobody booked this for the all-hands",
  "Still technically a portfolio demo",
  "Keep your presentation voice ready",
  "Public image, private reaction",
  "An interesting use of the meeting room",
  "The dress code applies offscreen",
  "Suitable for an informal raised eyebrow",
  "We didn't include this in onboarding",
  "Your boss might prefer the spreadsheet",
  "The client asked to see your work",
  "For the record, you clicked Draw",
  "Source link available for follow-up",
  "The conference room has excellent sightlines",
  "Hopefully the projector is still off",
  "Browsing is a bold interview technique",
  "It looked ordinary at thumbnail size",
  "Your annual review can omit this draw",
  "The visitors are sitting closer today",
  "Perhaps face the monitor away from reception",
  "Someone may remember this as research",
  "This wasn't in the client deck",
  "An unscheduled test of office acoustics",

  // References and stranger finds.
  "There are four corners. Count again",
  "The red room has no export settings",
  "A damn fine cup of image data",
  "Rosebud wasn't a filename",
  "Waiting for the monolith to render",
  "My God, it's full of thumbnails",
  "The owls left no EXIF",
  "All those moments, backed up somewhere",
  "I can open the pod bay folder",
  "The printer says PC LOAD LETTER",
  "There is always money in the backup",
  "The cake survived as a JPEG",
  "You are likely to be eaten by a folder",
  "Waiting for Godot's attachment",
  "This is not a pipe. It might be a file",
  "Bag End appears to contain a server",
  "The map is larger than the photograph",
  "Forty-two is a valid array index",
  "Please return your Babel library card",
  "This photograph has a portrait in the attic",
  "Schrödinger declined to preview it",
  "The ship has had all its pixels replaced",
  "The museum of missing captions is open",
  "Someone left a checksum in the margins",
  "At the bottom, another bottom",
  "We have misplaced the fourth wall",
  "You may already be in the contact sheet",
  "This scan counts as its own original",
  "The archive has a file on the archive",
  "Tomorrow's nostalgia arrived early",
];
