export const neutralMessages = [
  // Plain loading, new views, and unplanned draws.
  "Drawing a frame…",
  "Looking for the next frame…",
  "A moment between frames…",
  "Something new is on its way…",
  "Making room for another view…",
  "One frame at a time…",
  "Taking a closer look…",
  "Waiting for the next view…",
  "A little pause…",
  "Another view awaits…",
  "Looking a little further…",
  "Turning to the next frame…",
  "A new perspective awaits…",
  "Finding another view…",
  "Just a moment…",
  "Between one view and the next…",
  "A quiet moment…",
  "Looking beyond this frame…",
  "The next frame is on its way…",
  "A small pause for discovery…",
  "Seeing what comes next…",
  "Opening another window…",
  "Leaving room for surprise…",
  "A moment for the unexpected…",
  "Let's see what's next…",
  "Picking the next frame…",
  "There's more to see…",
  "A frame you haven't seen yet…",
  "A view without a plan…",
  "Nothing picked out in advance…",
  "A moment before the reveal…",
  "The next view is still loading…",
  "Somewhere we haven't looked…",
  "Letting the next frame load…",
  "A fresh draw…",
  "Something we haven't seen…",
  "Drawing something from the archive…",
  "Picking one at random…",
  "Searching through the pile…",
  "Pulling another moment…",
  "Finding something worth showing…",
  "Looking somewhere unexpected…",
  "Searching for a forgotten moment…",
  "Letting chance decide…",
  "Shuffling the archive…",
  "Opening another drawer…",
  "Digging a little deeper…",
  "Somewhere in here…",
  "Trusting randomness…",
  "Handing control to probability…",
  "Asking chance for directions…",
  "Leaving this one to fate…",
  "Searching for a hidden gem…",
  "Waiting for focus…",
  "Finding the subject…",
  "Looking through the viewfinder…",
  "Looking for visual evidence…",
  "Looking for accidental art…",
  "Searching for a different scene…",
  "A frame from an unfamiliar place…",
  "Waiting for the picture to arrive…",
  "Loading another slice of life…",
  "A small turn of the lens…",
  "A chance to notice something else…",
  "Moving to a different moment…",
  "The viewfinder is still open…",
  "A brief change of scenery…",
  "Letting this view take shape…",
  "One image on its way…",
  "Pausing at the next turn…",
  "Nothing to choose just yet…",
  "A short gap in the sequence…",
  "Holding a place for the image…",
  "The picture comes next…",
  "A few pixels to go…",
  "Keeping the viewfinder ready…",
  "A scene is coming through…",
  "Waiting on a little detail…",
  "This view needs a moment…",
  "The image is catching up…",
  "A new draw in progress…",
  "Passing through the collection…",
  "Taking a turn through elsewhere…",
  "A different place to look…",
  "Letting the scene come through…",
  "Looking without a destination…",
  "Moving on from this scene…",
  "The frame is still arriving…",
  "One picture before we move on…",
  "A scene beyond this pause…",
  "Making a little headway…",
  "The draw is still underway…",
  "Something else to look at…",
  "A moment off the usual path…",
  "No particular order today…",
  "Taking the collection as it comes…",
  "A place chosen by chance…",
  "Nothing planned for this view…",
  "Letting the order fall away…",
  "Skipping ahead without a map…",
  "One stop in a larger collection…",
  "An image beyond the familiar…",
  "The view can wait a beat…",
  "Giving this moment some room…",
  "A change in the line of sight…",
  "Passing the choice along…",
  "Seeing where the draw lands…",
  "A quiet shift of attention…",
  "Some distance from the last view…",
  "A picture among many…",
  "No destination set this time…",
  "An open space for the next image…",
  "A brief interval in the viewing…",
  "A scene to settle into…",
  "The next stop is undecided…",
  "A view taking its time…",
  "Drawing from a wider field…",
  "A small break in the pattern…",
  "Letting the selection arrive…",
  "A little distance between scenes…",
  "An image outside the routine…",
  "A place in the sequence opens…",
  "The collection continues from here…",
  "A view along another route…",
  "No route to retrace…",
  "Following the draw for a moment…",
  "A frame off the main road…",
  "Keeping an eye on the blank…",
  "This part takes a little time…",
  "The draw brings us somewhere else…",
  "A view past the usual landmarks…",
  "The draw reaches further today…",
  "A different moment to sit with…",
  "Letting the last image pass…",
  "A pause with somewhere to go…",
  "Seeing where this leads…",
  "The scene changes shortly…",
  "A new image for this space…",
  "Taking a step through the images…",
  "A different stretch of the world…",
  "The view is on its way here…",
  "An unscheduled look around…",
  "A moment chosen without a reason…",
  "The choice is still out of sight…",
  "A pause at an open window…",
  "Drawing beyond the last scene…",
  "The collection has another page…",
  "A scene with room to look…",
  "This space belongs to an image…",
  "A view further along the way…",
  "Waiting where the picture goes…",
  "The blank gives way shortly…",
  "Chance takes the next turn…",
  "A frame in transit…",

  // Requests and image data.
  "Waiting for image data",
  "Next draw in progress",
  "Fetching a public image",
  "Reading the response",
  "Preparing the viewing area",
  "The request is underway",

  "Image data is still arriving",
  "Loading the selected file",
  "Ready for another picture",
  "Waiting at the viewfinder",
  "One request in flight",
  "Checking the image source",
  "Retrieving this draw",
  "The picture needs another beat",
  "We have a little time to look",
  "Room for a different subject",
  "Bringing the image to the screen",
  "Following the source link",
  "Still on the way",
  "Opening the image data",
  "The view hasn't arrived yet",
  "Receiving the next picture",
  "From the source to here",
  "The picture hasn't reached us yet",
  "Reading what came back",
  "The screen is ready",
  "Keeping the image space clear",
  "Gathering the picture data",
  "Another image is in progress",
  "We'll have a view shortly",
  "Waiting for the file to open",
  "The request has left this window",
  "Retrieving a view from the source",
  "Getting the picture into place",
  "Image loading continues",
  "Next picture pending",
  "Loading at the source's pace",
  "An image is making its way here",
  "The file is still coming through",
  "For now, a little space",
  "Moving between pictures",
  "Another subject comes into view",
  "Past the last image",
  "Choosing where to look next",
  "Another place in the collection",
  "We can look further",

  // Moving through the collection.
  "Setting the last view aside",
  "On to another picture",
  "Somewhere else for a moment",
  "This draw goes its own way",
  "Across the collection",
  "Into the next image",
  "One more look through here",
  "Our next subject is undecided",
  "Taking the pictures out of order",
  "No preferred direction",
  "Let the next view arrive",
  "A stop we didn't arrange",
  "Here comes a different scene",
  "There isn't a route to follow",
  "We pick up elsewhere",
  "The order can change",
  "From here, anywhere",
  "Off to an unspecified place",
  "Next comes whatever comes",
  "Seeing what the source returns",
  "Each draw starts again",
  "No shortlist for this one",
  "The choice belongs to chance",
  "Some other point in the collection",
  "We'll see where this lands",
  "Picking without a preference",
  "Any image could be next",
  "Nothing marked for this draw",
  "Unplanned, as usual",
  "Plenty left to look through",
  "Leaving the sequence open",
  "We haven't chosen a subject",
  "Proceeding in no fixed order",
  "An arbitrary place to begin",
  "Giving the draw a moment",
  "The next image will set the scene",
  "Waiting for something to look at",
  "There's room for the whole picture",
  "Keeping the corners open",
  "Before the picture fills this space",

  // The space before an image.
  "The blank is temporary",
  "We pause here for the image",
  "Still looking through",
  "Nothing in the viewfinder yet",
  "The subject comes later",
  "Letting the screen catch up",
  "All set on this side",
  "Holding the view open",
  "Soon, something to inspect",
  "Just between pictures",
  "This is the space before the view",
  "Another picture takes the stage",
  "Waiting on the other end",
  "Keeping a place in the gallery",
  "We can leave a moment here",
  "The view is taking shape elsewhere",
  "Eyes on the next draw",
  "Picture first, caption later",
  "The next subject is still offscreen",
  "While the image travels",
  "Not much to see here yet",
  "We're between subjects",
  "When it arrives, we'll look",
  "This moment is still blank",
  "Past one picture, before another",
  "Our view is being retrieved",
  "The image will fill in the rest",
  "Fetching without a destination",
  "Reading across the collection",
  "Something beyond this window",
  "Looking where the draw points",
  "Another part of the public archive",
  "We haven't reached the image yet",
  "On the way to a new subject",
  "The gallery has room to continue",
  "For a moment, just the frame",
  "Keeping the picture in mind",
  "Next view requested",
  "Across another stretch of images",
  "This selection is still loading",

  // Following the next draw.
  "Almost at the viewing part",
  "The next scene comes from elsewhere",
  "Waiting to see what was selected",
  "Another draw, another place",
  "Passing from one subject to another",
  "The source has the picture",
  "We'll take the collection unsorted",
  "Receiving a little of elsewhere",
  "No subject picked by hand",
  "First the request, then the view",
  "Leaving the choice open",
  "The next picture is out there",
  "Taking whichever view comes next",
  "We have space for another",
  "This draw is still offstage",
  "Back to the collection",
  "Following an image to its source",
  "From a link to a view",
  "The request is ahead of the picture",
  "Settling into a brief wait",
  "Looking further into the collection",
  "The scene is still on the other side",
  "Another image for a closer look",
  "We can take the view as it comes",
  "With the next picture in mind",
  "The frame has a place ready",
  "Opening a view beyond this one",
  "Pausing before a different subject",
  "Picture data on the way",
  "The gallery waits for its next image",
  "Our next view is being fetched",
  "Loading a small part of the archive",
  "We're waiting at this end",
  "Something else will occupy this space",
];
