// Category weights stay independent of pool size, so adding jokes never makes them more frequent.
export const loadingMessages = [
  {
    category: "neutral",
    weight: 72,
    messages: [
      "Drawing a frame…",
      "Looking for the next frame…",
      "A moment between frames…",
      "Something new is on its way…",
      "Making room for another view…",
      "One frame at a time…",
      "Taking a closer look…",
      "Waiting for the next view…",
      "A little pause…",
      "Another view awaits…",
      "Looking a little further…",
      "Turning to the next frame…",
      "A new perspective awaits…",
      "Finding another view…",
      "Just a moment…",
      "Between one view and the next…",
      "A quiet moment…",
      "Looking beyond this frame…",
      "The next frame is on its way…",
      "A small pause for discovery…",
      "Seeing what comes next…",
      "Opening another window…",
      "Leaving room for surprise…",
      "A moment for the unexpected…",
      "Let's see what's next…",
      "Picking the next frame…",
      "There's more to see…",
      "A frame you haven't seen yet…",
      "A view without a plan…",
      "Nothing picked out in advance…",
      "A moment before the reveal…",
      "The next view is still loading…",
      "Somewhere we haven't looked…",
      "Letting the next frame load…",
      "A fresh draw…",
      "Something we haven't seen…",
      "Drawing something from the archive…",
      "Picking one at random…",
      "Searching through the pile…",
      "Pulling another moment…",
      "Finding something worth showing…",
      "Looking somewhere unexpected…",
      "Searching for a forgotten moment…",
      "Letting chance decide…",
      "Shuffling the archive…",
      "Opening another drawer…",
      "Digging a little deeper…",
      "Somewhere in here…",
      "Trusting randomness…",
      "Handing control to probability…",
      "Asking chance for directions…",
      "Leaving this one to fate…",
      "Searching for a hidden gem…",
      "Waiting for focus…",
      "Finding the subject…",
      "Looking through the viewfinder…",
      "Looking for visual evidence…",
      "Looking for accidental art…",
      "Searching for a different scene…",
      "A frame from an unfamiliar place…",
      "Waiting for the picture to arrive…",
      "Loading another slice of life…",
      "A small turn of the lens…",
      "A chance to notice something else…",
      "Moving to a different moment…",
      "The viewfinder is still open…",
      "A brief change of scenery…",
      "Letting this view take shape…",
      "One image on its way…",
      "Pausing at the next turn…",
      "Nothing to choose just yet…",
      "A short gap in the sequence…",
      "Holding a place for the image…",
      "The picture comes next…",
      "A few pixels to go…",
      "Keeping the viewfinder ready…",
      "A scene is coming through…",
      "Waiting on a little detail…",
      "This view needs a moment…",
      "The image is catching up…",
      "A new draw in progress…",
      "Passing through the collection…",
      "Taking a turn through elsewhere…",
      "A different place to look…",
      "Letting the scene come through…",
      "Looking without a destination…",
      "Moving on from this scene…",
      "The frame is still arriving…",
      "One picture before we move on…",
      "A scene beyond this pause…",
      "Making a little headway…",
      "The draw is still underway…",
      "Something else to look at…",
      "A moment off the usual path…",
      "No particular order today…",
      "Taking the collection as it comes…",
      "A place chosen by chance…",
      "Nothing planned for this view…",
      "Letting the order fall away…",
      "Skipping ahead without a map…",
      "One stop in a larger collection…",
      "An image beyond the familiar…",
      "The view can wait a beat…",
      "Giving this moment some room…",
      "A change in the line of sight…",
      "Passing the choice along…",
      "Seeing where the draw lands…",
      "A quiet shift of attention…",
      "Some distance from the last view…",
      "A picture among many…",
      "No destination set this time…",
      "An open space for the next image…",
      "A brief interval in the viewing…",
      "A scene to settle into…",
      "The next stop is undecided…",
      "A view taking its time…",
      "Drawing from a wider field…",
      "A small break in the pattern…",
      "Letting the selection arrive…",
      "A little distance between scenes…",
      "An image outside the routine…",
      "A place in the sequence opens…",
      "The collection continues from here…",
      "A view along another route…",
      "No route to retrace…",
      "Following the draw for a moment…",
      "A frame off the main road…",
      "Keeping an eye on the blank…",
      "This part takes a little time…",
      "The draw brings us somewhere else…",
      "A view past the usual landmarks…",
      "The draw reaches further today…",
      "A different moment to sit with…",
      "Letting the last image pass…",
      "A pause with somewhere to go…",
      "Seeing where this leads…",
      "The scene changes shortly…",
      "A new image for this space…",
      "Taking a step through the images…",
      "A different stretch of the world…",
      "The view is on its way here…",
      "An unscheduled look around…",
      "A moment chosen without a reason…",
      "The choice is still out of sight…",
      "A pause at an open window…",
      "Drawing beyond the last scene…",
      "The collection has another page…",
      "A scene with room to look…",
      "This space belongs to an image…",
      "A view further along the way…",
      "Waiting where the picture goes…",
      "The blank gives way shortly…",
      "Chance takes the next turn…",
      "A frame in transit…",
    ],
  },
  {
    category: "archive",
    weight: 23,
    messages: [
      "Bringing another frame into focus…",
      "Looking through the archive…",
      "Somewhere in the contact sheet…",
      "A glimpse from another time…",
      "Turning a page in the archive…",
      "Looking past the edges…",
      "A brief pause in the darkroom…",
      "Waiting for the image to develop…",
      "Another exposure awaits…",
      "Following a loose thread…",
      "A detail worth a second look…",
      "Somewhere beyond the viewfinder…",
      "A small window into elsewhere…",
      "Looking between the negatives…",
      "A frame from somewhere else…",
      "One more glimpse…",
      "An unplanned composition…",
      "A pause before the next exposure…",
      "A little light from elsewhere…",
      "Off the beaten contact sheet…",
      "At the edge of the archive…",
      "An unexpected point of view…",
      "Looking for a different angle…",
      "Another corner of the internet…",
      "Pulling a frame from the stack…",
      "An image without its caption…",
      "A page we haven't opened…",
      "Somewhere in an unnamed folder…",
      "A loose print from the archive…",
      "A moment someone left behind…",
      "Opening an old contact sheet…",
      "One frame, very little context…",
      "Looking through the unsorted pile…",
      "An exposure with a missing date…",
      "A scene outside our usual route…",
      "A picture far from its source…",
      "Opening another digital time capsule…",
      "Disturbing the digital sediment…",
      "Excavating old pixels…",
      "Archaeology, but with screenshots…",
      "Digging through digital fossils…",
      "Unearthing a little history…",
      "A file with its own history…",
      "Looking beyond the filenames…",
      "Opening the folder within the folder…",
      "Descending another directory level…",
      "Searching past the backups…",
      "Looking beyond copy (3)…",
      "Checking somewhere past screenshots…",
      "Looking for accidental composition…",
      "Searching for accidental cinema…",
      "Looking for a trace of a story…",
      "Finding a scene between the scenes…",
      "A view from the cutting room floor…",
      "A frame without the rest of the reel…",
      "An image with the date worn off…",
      "Something outside the usual crop…",
      "A glimpse between the takes…",
      "A picture without the backstory…",
      "A forgotten corner of the screen…",
      "Following the grain…",
      "Looking for the light in this one…",
      "Another scene from the pile…",
      "Waiting at the edge of the lens…",
      "A shot from outside the sequence…",
      "A small find in a large archive…",
      "A print without a place in the album…",
      "Turning over another loose frame…",
      "Lifting the tissue between prints…",
      "A pencil note on the reverse…",
      "Sliding a negative toward the light…",
      "A reel from the lower shelf…",
      "Checking the sleeve for a date…",
      "Light caught on an ordinary day…",
      "A street kept in a photograph…",
      "Dust along the binding…",
      "A face outside the caption…",
      "The stamp outlasted the address…",
      "A thumbprint on the border…",
      "An envelope full of afternoons…",
      "A date in someone else's hand…",
      "A crease through the background…",
      "The margin holds a pencil mark…",
      "Reading the light on an old wall…",
      "A print slipped between pages…",
      "An afternoon on a strip of film…",
      "A small room kept in silver…",
      "A label loosening at the corner…",
      "One shutter click, years later…",
      "A landscape filed under numbers…",
      "A building before its new name…",
      "A shelf with uneven stacks…",
      "A scene kept by the scanner…",
      "An old export coming through…",
      "A photograph behind the paperwork…",
      "A handwritten place we can't read…",
      "A roll that took the long way…",
      "A picture carried between machines…",
      "A familiar street at another date…",
      "A corner the photographer kept…",
      "A shadow across the emulsion…",
      "A sleeve with room for one more…",
      "A small rectangle of daylight…",
      "A view from before the renovation…",
      "A scan with its borders intact…",
      "The background has its own history…",
      "An album held together by habit…",
      "A photograph waiting in an envelope…",
      "A detail the caption passed over…",
      "A chair at the edge of a shot…",
      "A window in someone else's day…",
      "A pause recorded on film…",
      "A snapshot kept through several moves…",
      "The paper remembers the fold…",
      "A horizon from a different decade…",
      "A print that missed the exhibition…",
      "A crop made before this screen…",
      "Someone stood here with a camera…",
      "A few seconds kept from a reel…",
      "A doorway in an old exposure…",
      "A file carried through the years…",
      "A scene just off the index…",
      "A numbered box on a high shelf…",
      "A copy with a faint border…",
      "The scan catches a little dust…",
      "A brief record of the weather…",
      "The afternoon survived the upload…",
      "A photograph with softened corners…",
      "Reading an old image in new light…",
      "A trace left by the lens…",
      "The shelf ends further along…",
      "A sheet held up to the light…",
      "A few marks from the handling…",
      "A quiet scene in a crowded box…",
      "A print passed between hands…",
      "The label names a different town…",
      "A scene copied off an old drive…",
      "An instant kept beyond its day…",
      "A reflection on a strip of film…",
      "The edges show a little age…",
      "A record of where the light fell…",
      "A camera stopped here once…",
      "One rectangle from a longer reel…",
      "A photograph awaiting a caption…",
      "A street before the signs changed…",
      "A view the album couldn't fit…",
      "A small mark beside the frame…",
      "A loose end in the catalogue…",
      "A contact print under the lamp…",
      "The folder kept the original name…",
      "A box with a crossed-out label…",
      "An image behind a faded tab…",
      "A few seconds from another room…",
      "A print under the last divider…",
      "A border the crop left behind…",
      "A scene held in a glass plate…",
      "A photograph between two receipts…",
      "A detail near the sprocket holes…",
    ],
  },
  {
    category: "playful",
    weight: 4,
    messages: [
      "Taking the scenic route…",
      "Curiosity has the controls…",
      "No idea what comes next…",
      "A tiny detour through elsewhere…",
      "The internet has many drawers…",
      "A lucky dip in the pixels…",
      "Somewhere, a cat is supervising…",
      "A frame with no appointment…",
      "The pixels are keeping us guessing…",
      "Wandering with purpose. Mostly…",
      "A small expedition…",
      "Let's see what turns up…",
      "This could be anything…",
      "No promises about the next frame…",
      "Proceeding with dubious confidence…",
      "Opening Pandora's folder…",
      "Statistically, a questionable idea…",
      "You clicked it. We're committed…",
      "Randomness has declined to comment…",
      "The next frame wasn't in the brief…",
      "We didn't storyboard this bit…",
      "A plan would spoil the surprise…",
      "Rolling the dice on good taste…",
      "This one may require context…",
      "Hopefully nothing cursed this time…",
      "The folder names aren't helping…",
      "Leaving this to chance. Again…",
      "The preview is also a surprise…",
      "Finding the next accident…",
      "Choosing with absolutely no context…",
      "Rolling the archive dice…",
      "Selecting without supervision…",
      "Consulting the entropy department…",
      "Randomness is doing its best…",
      "The algorithm has no idea either…",
      "This choice wasn't peer-reviewed…",
      "Applying scientific randomness…",
      "Pretending this is deterministic…",
      "Invoking the random number gods…",
      "Negotiating with the backend…",
      "The server is making up its mind…",
      "Politely asking for another one…",
      "Doing computer things…",
      "Bits are moving. Probably…",
      "Packets are being encouraged…",
      "Searching the tubes…",
      "Reticulating pixels…",
      "Warming up questionable machinery…",
      "Everything is under control-ish…",
      "A very normal loading screen…",
      "Please ignore the machinery…",
      "Looking for a frame with personality…",
      "Trying not to pick the boring one…",
      "Attempting to locate composition…",
      "Hunting for a decent crop…",
      "Adjusting imaginary focus…",
      "Checking exposure. Metaphorically…",
      "Developing absolutely nothing…",
      "Making pixels look intentional…",
      "Finding a frame nobody asked for…",
      "This one could be art…",
      "This one could also be garbage…",
      "Art is subjective. Loading is not…",
      "Manage expectations accordingly…",
      "You clicked Draw. This is on you…",
      "The button has been pressed…",
      "Choices were made…",
      "Consequences are loading…",
      "Regret buffering…",
      "Please complain to probability…",
      "Randomness accepts no liability…",
      "Taste not guaranteed…",
      "Context not guaranteed…",
      "Results may vary dramatically…",
      "Lowering expectations slightly…",
      "Calibrating disappointment…",
      "Searching for complete nonsense…",
      "Could go either way…",
      "An image exists. Allegedly…",
      "Sources say pixels are imminent…",
      "The situation is developing…",
      "The archive has declined to comment…",
      "Past-you had reasons. Probably…",
      "Somewhere, metadata is judging us…",
      "There are always more folders…",
      "Looking for final_final_2…",
      "A naming convention would've helped…",
      "Treating folders as suggestions…",
      "Previous-you left no documentation…",
      "Technical debt, but make it visual…",
      "Supporting historical nonsense…",
      "Works on my archive…",
      "Reproducing randomness locally…",
      "Awaiting asynchronous life choices…",
      "Promise pending…",
      "Yielding briefly to the event loop…",
      "The DOM is considering its options…",
      "Adding tasteful blur to uncertainty…",
      "GPU has been informed…",
      "Optimizing vibes…",
      "Making waiting look intentional…",
      "Please admire the loading state…",
      "Someone spent too long on the easing…",
      "Premium waiting in progress…",
      "Handcrafted latency…",
      "Artisanal loading…",
      "Locally sourced randomness…",
      "Free-range pixels incoming…",
      "Small-batch frame selection…",
      "Farm-to-table pixels…",
      "Single-origin randomness…",
      "Bespoke waiting experience…",
      "The pixels are resting…",
      "Giving the JPEG some space…",
      "The next frame is finding itself…",
      "The image is almost emotionally ready…",
      "Negotiations with the pixels continue…",
      "Brace for tonal inconsistency…",
      "Mood continuity not guaranteed…",
      "Preparing an abrupt genre change…",
      "Continuity department unavailable…",
      "Preparing an unexpected cut…",
      "Finding B-roll nobody requested…",
      "Roll camera. Maybe…",
      "And… something…",
      "Take 37…",
      "One more take…",
      "Fixing it in post…",
      "Post-production has concerns…",
      "The editor has left the building…",
      "No color grading can explain this…",
      "Aspect ratio emotionally unavailable…",
      "Searching for a plot twist…",
      "Cutting to something unrelated…",
      "Chance skipped the introductions…",
      "A coin toss with a file extension…",
      "The curator stepped out for lunch…",
      "The tripod is largely ceremonial…",
      "Nobody briefed the shutter…",
      "The lens cap has reservations…",
      "A JPEG at its own pace…",
      "The preview missed the rehearsal…",
      "This crop was a judgment call…",
      "Our shortlist is the entire archive…",
      "The selection committee is a number…",
      "The dice don't read captions…",
      "Taste is outside this function…",
      "The thumbnail gave little away…",
      "An orderly queue of unrelated things…",
      "The frame chose an inconvenient time…",
      "A detour approved by nobody…",
      "The plot can catch up later…",
      "Composition by coincidence…",
      "A composition the grid can't explain…",
      "A histogram with private opinions…",
      "White balance can only do so much…",
      "The horizon has other priorities…",
      "Depth of field, shallow planning…",
      "The bokeh wasn't consulted…",
      "Some blur was inevitable…",
      "An exposure to uncertain taste…",
      "The camera avoided eye contact…",
      "A still life with scheduling issues…",
      "The pixels came separately…",
      "The file size suggests commitment…",
      "An image with a long commute…",
      "The loading bar is off duty…",
      "We left suspense enabled…",
      "The pause wasn't in the estimate…",
      "A request with modest ambitions…",
      "One fetch away from a picture…",
      "The network took a brief walk…",
      "Latency found a seat…",
      "Awaiting a less abstract rectangle…",
      "The placeholder is getting attached…",
      "The spinner declined the role…",
      "This blank has a short contract…",
      "The skeleton wants more screen time…",
      "A perfectly legal use of a div…",
      "The alt text got here first…",
      "The cache remembers selectively…",
      "A byte is taking the stairs…",
      "The callback missed its cue…",
      "A promise with something to prove…",
      "The response needs an entrance…",
      "The progress bar wanted specifics…",
      "An integer made this decision…",
      "The seed has no artistic training…",
      "Uniform distribution, uneven taste…",
      "A shuffle with limited credentials…",
      "The odds keep their own counsel…",
      "Chance doesn't take requests…",
      "The coin landed out of shot…",
      "A sample size of one picture…",
      "The index picked a side…",
      "We outsourced choice to arithmetic…",
      "The catalogue lacks a punchline…",
      "The filing cabinet runs deep…",
      "An unlabeled box seems confident…",
      "The archive sorts by its own rules…",
      "The dust jacket came off first…",
      "The film came with loose ends…",
      "The darkroom has office hours…",
      "An enlarger with modest ambitions…",
      "The scanner remembers every crease…",
      "The loupe found something small…",
      "A test print of our judgment…",
      "The shelf has no recommendations…",
      "A folder named misc knew too much…",
      "The readme stayed in another folder…",
      "Untitled was an editorial choice…",
      "A backup of a questionable decision…",
      "The extension tells half the story…",
      "The filename peaked at IMG…",
      "Someone trusted the default settings…",
      "This export escaped the desktop…",
      "The draft survived the cleanup…",
      "The bin missed one…",
      "The naming scheme ended abruptly…",
      "A directory with room for doubt…",
      "We're between informed decisions…",
      "The explanation arrives separately…",
      "The context took another flight…",
      "The caption called in sick…",
      "An establishing shot of uncertainty…",
      "The continuity error starts here…",
      "A subplot in the wrong folder…",
      "The credits may clear this up…",
      "The camera is technically rolling…",
      "The storyboard ends at the button…",
      "An intermission without refreshments…",
      "The final cut has rough edges…",
      "The director asked for less context…",
      "A freeze-frame with unfinished plans…",
    ],
  },
  {
    category: "easterEgg",
    weight: 1,
    messages: [
      "The owls are not what they seem…",
      "Life, the universe, and this frame…",
      "There is no spoon. Just pixels…",
      "These may be the frames you seek…",
      "Checking if this is safe for work…",
      "Avoiding career-ending material…",
      "Looking for a frame HR would allow…",
      "Probably safe. Probably…",
      "Attempting responsible randomness…",
      "Please remain professionally calm…",
      "Consulting an imaginary moderator…",
      "Rolling for workplace compatibility…",
      "The next frame has no references…",
      "Hoping your boss likes abstract art…",
      "An awkward screenshot is possible…",
      "Your browser history has questions…",
      "Checking workplace compatibility…",
      "An informal NSFW risk assessment…",
      "Looking for something safe-ish…",
      "Does this need an explanation…?",
      "Looking for something HR-neutral…",
      "Attempting professional randomness…",
      "Would legal tolerate this frame…?",
      "Hoping this suits a screen share…",
      "Trying not to summon HR…",
      "Keeping things reasonably employable…",
      "Hoping your manager walks past…",
      "Seeking plausible deniability…",
      "This may be difficult to explain…",
      "Context would not help anyway…",
      "We can explain. Probably…",
      "You saw nothing…",
      "Nothing to report here…",
      "Please remain professionally composed…",
      "Dignity not guaranteed…",
      "The archive knows what you did…",
      "Some files were best left forgotten…",
      "The archive has seen things…",
      "The archive refuses to elaborate…",
      "Some folders deserve caution…",
      "EXIF has entered the chat…",
      "CSS cannot save us now…",
      "The happy path remains theoretical…",
      "Searching outside the test coverage…",
      "Emotionally complex promise pending…",
      "The next frame has asked for a lawyer…",
      "This JPEG has diplomatic immunity…",
      "The contact sheet pleads the fifth…",
      "Your screen share adds stakes…",
      "The meeting chose an interesting time…",
      "A polite cough may follow…",
      "The agenda didn't mention this…",
      "A file best opened after standup…",
      "The projector makes this communal…",
      "The filename provides no alibi…",
      "HR prefers a smaller sample size…",
      "Your manager has peripheral vision…",
      "A discreet glance at the audience…",
      "The archive lacks a dress code…",
      "This folder missed orientation…",
      "A screensaver might be more prudent…",
      "The office Wi-Fi picked today…",
      "An innocent tab in difficult company…",
      "The presenter view has limits…",
      "A brief test of meeting etiquette…",
      "The crop may carry the explanation…",
      "The boardroom wasn't the target venue…",
      "Someone may ask about the source…",
      "A file with poor interview manners…",
      "The risk register needs a thumbnail…",
      "An awkward silence needs no caption…",
      "The title sounded perfectly ordinary…",
      "Safe for work is a broad brief…",
      "The audience makes this interesting…",
      "A small gamble on office culture…",
      "The folder was marked personal…",
      "A preview for a smaller window…",
      "The compliance slide comes later…",
      "A frame beyond the approved deck…",
      "We may call this visual research…",
      "The mute button won't help much…",
      "An impromptu lesson in tab selection…",
      "The chair turns toward your screen…",
      "Your résumé omitted this collection…",
      "A file with questionable references…",
      "The offsite album stayed on site…",
      "Nobody requested a live demonstration…",
      "The witness is a lossless PNG…",
    ],
  },
];

export function pickLoadingMessage(exclude: readonly string[]): string {
  let roll = Math.random() * loadingMessages.reduce((total, pool) => total + pool.weight, 0);
  const group =
    loadingMessages.find((pool) => {
      roll -= pool.weight;
      return roll < 0;
    }) ?? loadingMessages[0];
  const messages = group?.messages.filter((message) => !exclude.includes(message)) ?? [];
  return messages[Math.floor(Math.random() * messages.length)] ?? "Drawing a frame…";
}
